version: "3"
networks:
  service-net:

services:
  frontend-app:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - service-net

  backend-app:
    build:
      context: ./backend
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "YOUR PASSWORD"
      DB_HOST: "database"
      DB_NAME: "postgres"
# Uncomment to allow direct access from host system (e.g. for testing using Postman)
#    ports:
#      - "8000:8000"

    # Use http://backend-app/ as the base hostname
    networks:
      - service-net

  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: "YOUR PASSWORD"
    # map directories
    # Every .sql or .sh script in the mapped directory is executed on container startup
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

# Uncomment to map ports allowing direct access to Database.
# Convenient when debugging.
#    ports:
#      - "5432:5432"
    networks:
      - service-net
