version: "3"
networks:
  internal:

services:
  frontend-app:
    build:
      context: ./frontend
    environment:
      PORT: "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - internal

  backend-app:
    build:
      context: ./backend
    environment:
      PORT: "${BACK_PORT}"
# Uncomment to allow direct access from host system (e.g. for testing using Postman)
#    ports:
#      - "${BACK_PORT}:${BACK_PORT}"

    # Use http://backend-app/ as the base hostname
    networks:
      - internal

  database:
    image: postgres:13.2-alpine
    # map directories
    # Every .sql or .sh script in the mapped directory is executed on container startup
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

# Uncomment to map ports allowing direct access to Database.
# Convenient when debugging.
#    ports:
#      - "${DB_PORT}:${DB_PORT}"
    networks:
      - internal
